"""Render exact runtime-deformed contact meshes, including real extracted core/wreck.
Input is generated by prepare-model-v5-snapshots.mjs; source textures stay packed.
"""
import bpy, os, json, math
from mathutils import Vector
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(ROOT,'assets-source','pose-review','v5');os.makedirs(OUT,exist_ok=True)
with open(os.path.join(ROOT,'artifacts','robot-v5-contact-poses.json'),encoding='utf8') as f: shots=json.load(f)
def vector(values): return Vector((values[0],-values[2],values[1]))
for obj in bpy.data.objects: obj.hide_render=True
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=32;scene.cycles.use_denoising=True
scene.render.resolution_x=1000;scene.render.resolution_y=700;scene.render.resolution_percentage=100
scene.view_settings.view_transform='AgX'
world=scene.world;world.use_nodes=True;world.node_tree.nodes.clear()
bg=world.node_tree.nodes.new('ShaderNodeBackground');bg.inputs[0].default_value=(.035,.05,.075,1);bg.inputs[1].default_value=.25
out=world.node_tree.nodes.new('ShaderNodeOutputWorld');world.node_tree.links.new(bg.outputs[0],out.inputs[0])
def light(name,loc,energy,color,size):
 d=bpy.data.lights.new(name,'AREA');d.energy=energy;d.color=color;d.size=size
 o=bpy.data.objects.new(name,d);bpy.context.collection.objects.link(o);o.location=loc;o.rotation_euler=(Vector((0,0,1))-o.location).to_track_quat('-Z','Y').to_euler()
light('Cold_Key',(1,-4,6),450,(.61,.79,1),5);light('Warm_Edge',(-4,2,4),600,(1,.64,.3),4)
bpy.ops.mesh.primitive_plane_add(size=100,location=(0,0,-.014));floor=bpy.context.object
mat=bpy.data.materials.new('Contact_Review_Floor');mat.use_nodes=True;p=mat.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(.028,.045,.062,1);p.inputs['Roughness'].default_value=.48;p.inputs['Metallic'].default_value=.25;floor.data.materials.append(mat)
camera_data=bpy.data.cameras.new('Contact_Camera');camera=bpy.data.objects.new('Contact_Camera',camera_data);bpy.context.collection.objects.link(camera);camera_data.type='ORTHO';scene.camera=camera
for shot in shots:
 created=[];materials=[];vertices=[]
 for item in shot['meshes']:
  name=item['material'].split('.')[0];base=bpy.data.materials.get(name)
  material=base.copy() if base else bpy.data.materials.new('Review_Metal');material.use_nodes=True;materials.append(material)
  material.node_tree.animation_data_clear();shader=material.node_tree.nodes.get('Principled BSDF')
  shader.inputs['Base Color'].default_value=(*item['color'],1);shader.inputs['Emission Color'].default_value=(*item['emissive'],1);shader.inputs['Emission Strength'].default_value=item['intensity']
  coords=[vector(item['positions'][i:i+3]) for i in range(0,len(item['positions']),3)];vertices.extend(coords)
  indices=item['indices'] or list(range(len(coords)));faces=[indices[i:i+3] for i in range(0,len(indices),3)]
  mesh=bpy.data.meshes.new(item['name']);mesh.from_pydata(coords,[],faces);mesh.update();mesh.materials.append(material)
  uv=mesh.uv_layers.new(name='UVMap')
  for loop in mesh.loops:
   i=loop.vertex_index*2;uv.data[loop.index].uv=item['uvs'][i:i+2]
  for polygon in mesh.polygons: polygon.use_smooth=True
  mesh.normals_split_custom_set_from_vertices([vector(item['normals'][i:i+3]) for i in range(0,len(item['normals']),3)])
  obj=bpy.data.objects.new(item['name'],mesh);bpy.context.collection.objects.link(obj);created.append(obj)
 for source in shot['lights']:
  data=bpy.data.lights.new('Actual_Robot_Lamp','SPOT' if source['type']=='spot' else 'POINT');data.color=source['color'];data.energy=source['intensity']*22;data.use_shadow=False;data.shadow_soft_size=.08
  obj=bpy.data.objects.new('Actual_Robot_Lamp',data);bpy.context.collection.objects.link(obj);created.append(obj);obj.location=vector(source['position'])
  if source['type']=='spot':
   data.spot_size=source['angle']*2;data.spot_blend=.65;obj.rotation_euler=(vector(source['target'])-obj.location).to_track_quat('-Z','Y').to_euler()
 minimum=Vector((min(p.x for p in vertices),min(p.y for p in vertices),min(p.z for p in vertices)))
 maximum=Vector((max(p.x for p in vertices),max(p.y for p in vertices),max(p.z for p in vertices)))
 focus=Vector(((minimum.x+maximum.x)/2,0,(minimum.z+maximum.z)/2));camera.location=focus+Vector((.9,-11,3.1));camera.rotation_euler=(focus-camera.location).to_track_quat('-Z','Y').to_euler()
 camera_data.ortho_scale=max(6.5,maximum.x-minimum.x+1.1,(maximum.z-minimum.z+.9)*1000/700)
 bpy.context.view_layer.update();scene.render.filepath=os.path.join(OUT,shot['name']+'.png');bpy.ops.render.render(write_still=True)
 for obj in created:
  data=obj.data;bpy.data.objects.remove(obj,do_unlink=True)
  if isinstance(data,bpy.types.Mesh): bpy.data.meshes.remove(data)
  else: bpy.data.lights.remove(data)
 for material in materials:bpy.data.materials.remove(material)
print('Rendered',len(shots),'exact V5 runtime contact frames to',OUT)
