// Generated by assets-source/posters/prepare.py; provenance in public/assets/posters/manifest.json.
export const POSTER_ATLAS = {"url": "/assets/posters/belobog-posters.webp", "size": [1024, 1536]};
export const POSTER_CATALOG = {
  "mining-helmet": {
    "aspect": 0.7142857142857143,
    "rect": [
      43,
      8,
      170,
      238
    ]
  },
  "geomarrow": {
    "aspect": 0.7142857142857143,
    "rect": [
      299,
      8,
      170,
      238
    ]
  },
  "warning": {
    "aspect": 0.7142857142857143,
    "rect": [
      555,
      8,
      170,
      238
    ]
  },
  "bottles": {
    "aspect": 0.7100840336134454,
    "rect": [
      811,
      8,
      169,
      238
    ]
  },
  "workshop-glass": {
    "aspect": 0.7016806722689075,
    "rect": [
      44,
      264,
      167,
      238
    ]
  },
  "fight-fist": {
    "aspect": 0.7016806722689075,
    "rect": [
      300,
      264,
      167,
      238
    ]
  },
  "coffee": {
    "aspect": 0.7100840336134454,
    "rect": [
      555,
      264,
      169,
      238
    ]
  },
  "sewing-machine": {
    "aspect": 0.7142857142857143,
    "rect": [
      811,
      264,
      170,
      238
    ]
  },
  "medical": {
    "aspect": 0.7394957983193278,
    "rect": [
      40,
      520,
      176,
      238
    ]
  },
  "falling-rocks": {
    "aspect": 0.7100840336134454,
    "rect": [
      299,
      520,
      169,
      238
    ]
  },
  "boxer": {
    "aspect": 0.6428571428571429,
    "rect": [
      563,
      520,
      153,
      238
    ]
  },
  "workshop-notice": {
    "aspect": 1.1542857142857144,
    "rect": [
      795,
      520,
      202,
      175
    ]
  },
  "newspaper": {
    "aspect": 1.5412844036697249,
    "rect": [
      44,
      776,
      168,
      109
    ]
  },
  "wanted-sampo-gepard": {
    "aspect": 0.8361344537815126,
    "rect": [
      284,
      776,
      199,
      238
    ]
  },
  "wanted-danheng-pela": {
    "aspect": 0.8235294117647058,
    "rect": [
      542,
      776,
      196,
      238
    ]
  },
  "wanted-march-pela": {
    "aspect": 0.7521008403361344,
    "rect": [
      806,
      776,
      179,
      238
    ]
  },
  "wanted-danheng-gepard": {
    "aspect": 0.7792207792207793,
    "rect": [
      38,
      1032,
      180,
      231
    ]
  },
  "wanted-sampo-pela": {
    "aspect": 0.8248847926267281,
    "rect": [
      294,
      1032,
      179,
      217
    ]
  },
  "wanted-march-gepard": {
    "aspect": 0.811965811965812,
    "rect": [
      545,
      1032,
      190,
      234
    ]
  },
  "wanted-trailblazer-gepard": {
    "aspect": 0.7719298245614035,
    "rect": [
      808,
      1032,
      176,
      228
    ]
  },
  "provided-wanted-redhair": {
    "aspect": 0.7478991596638656,
    "rect": [
      39,
      1288,
      178,
      238
    ]
  },
  "provided-wanted-grayhair": {
    "aspect": 0.7478991596638656,
    "rect": [
      295,
      1288,
      178,
      238
    ]
  }
};
